#include "pch.h"
#include "MouseEventHandlers.h"
#include <common/logger/logger.h> // adjust include paths as needed
#include <common/interop/shared_constants.h>

namespace
{
    // Check if this mouse event was injected by KeyboardManager to avoid loops
    bool GeneratedByKBM(const MSLLHOOKSTRUCT* mouseData)
    {
        return (mouseData->dwExtraInfo & CommonSharedConstants::KEYBOARDMANAGER_INJECTED_FLAG) != 0;
    }
}


namespace MouseEventHandlers
{
    intptr_t HandleSingleMouseRemapEvent(KeyboardManagerInput::InputInterface& ii, const MSLLHOOKSTRUCT* mouseData, WPARAM wParam, State& state) noexcept
    {
        // Check if event generated by us (if you have such a check for mouse, add here)
        // For now, assume no loop prevention

        // Example remap map: left click -> right click
        // You can later replace this with state-based remapping logic

        // Only handle mouse button down/up messages
        bool isButtonDown = (wParam == WM_LBUTTONDOWN || wParam == WM_RBUTTONDOWN || wParam == WM_MBUTTONDOWN);
        bool isButtonUp = (wParam == WM_LBUTTONUP || wParam == WM_RBUTTONUP || wParam == WM_MBUTTONUP);

        if (!isButtonDown && !isButtonUp)
        {
            return 0; // pass through all other mouse events
        }

        INPUT input{};
        input.type = INPUT_MOUSE;

        // Example: remap left click to right click
        if (wParam == WM_LBUTTONDOWN)
        {
            input.mi.dwFlags = MOUSEEVENTF_RIGHTDOWN;
        }
        else if (wParam == WM_LBUTTONUP)
        {
            input.mi.dwFlags = MOUSEEVENTF_RIGHTUP;
        }
        else
        {
            // For other buttons, just pass through (or add your remaps)
            return 0;
        }

        // Set mouse coordinates for input (optional, usually 0 means current position)
        input.mi.dx = mouseData->pt.x;
        input.mi.dy = mouseData->pt.y;
        input.mi.dwExtraInfo = KeyboardManagerConstants::KEYBOARDMANAGER_SUPPRESS_FLAG; // Mark event as generated by us

        UINT sentCount = SendInput(1, &input, sizeof(INPUT));
        if (sentCount != 1)
        {
            Logger::error(L"SendInput failed for mouse remap");
        }

        return 1; // suppress original left click event
    }

    intptr_t HandleMouseWheelRemapEvent(KeyboardManagerInput::InputInterface& ii, const MSLLHOOKSTRUCT* mouseData, WPARAM wParam, State& state) noexcept
    {
        // TODO: Implement mouse wheel remapping logic here
        return 0;
    }

    intptr_t HandleAppSpecificMouseShortcutRemapEvent(KeyboardManagerInput::InputInterface& ii, const MSLLHOOKSTRUCT* mouseData, WPARAM wParam, State& state) noexcept
    {
        // TODO: Implement app-specific mouse shortcut remapping here
        return 0;
    }
}
